name: Print Software Versions
on:
  push:
    branches: main
jobs:
  PrintAppServerVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js version
        run: node --version
  PrintDBServerVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Print PostgreSQL version
        run: psql --version
